### ISSUE TITLE
Investigate if cookie banner reappears across GOV.UK services

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk_template#243]
From `vincent_p_dwp` on the cross Government Slack

> Question: The cookie JS we all use to determine if we have seen the “blue bar” message, is in client-side JS. Does this persist between services? It looks like it is only persisted on the domain. So for example, If I visit any Gov.UK site it should be fine. But if I visited a service not on a GovUK domain, the user would have to agree again? Do I understand that correctly?

We need to check if the cookie bar persists across services, close if this is the case 😄

**Comment by alexmuller** [comment]
I believe it's intentional that the cookie bar reappears on every different service, because every service will probably use different cookies.

For GOV.UK we set the cookie on `www.gov.uk` so it won't apply to other services.

**Comment by vipickering** [comment]
@alexmuller thanks Alex, that's very useful :-)

Allow me to explain my train of thought for this question.

We currently use client-side JS in order to set the cookie, check if it exists and decide if we are going to show the blue bar message.

If a user has JS disabled, they see this message all the time. Granted they can use the skiplink (which is just before it) but it can still be a pain for the user to see on every page.

It seems like a better approach would be to have Node generate the cookie, perform the checks to see if it exists and then feed to Nunjucks, if the message should be displayed or not. Not only could we remove this annoying niggle from the UI for non-JS users, we could save downloading additional code, the extra http request etc.

The reason I was asking, was because I am interested in implementing the above Node approach and wanted to check I wasn't going to be forking off and doing my own thing. But if the cookies are service dependant, this isn't an issue and I can go the Node route.

**Comment by dsingleton** [comment]
@vipickering bit more context;

Because 99% of www.gov.uk's content is static and parts of the GOV.UK architecture are designed around content being highly cachable. This gives reduced server load, improved user performance, and robustness  if there are technical problems. Fun fact, the entire www.gov.uk infrastructure could go away and users would happily get (cached) content from the CDN :)

Varying caching by cookie makes that much much more difficult and less reliable, so it's done client side. [1] It's the same reason we do AB testing via JS rather than server side. Any variance by cookie on www.gov.uk is done via JS as a result.

> The reason I was asking, was because I am interested in implementing the above Node approach and wanted to check I wasn't going to be forking off and doing my own thing. But if the cookies are service dependant, this isn't an issue and I can go the Node route.

That sounds like a good fit for your service 👍 . The way services use cookies is going to be pretty different from www.gov.uk, with inherently more state, so it makes sense to consider cookies per service. A possible rule of thumb would be if a service is _using_ cookies server side, then it's cookie consent might need to be managed server side too. 

If thats a common pattern for services then we can probably improve `govuk_template` to make that easier - or allow consumer of `govuk_template` to pick a client or server side approach without much work. Thats not something we'd be looking at in the near future, but something to think about, and i'd be interested to hear how the implementation on your service goes :)

[1] Given cookies on www.gov.uk are only set/used in JS, it _may_ be possible to **not** show the cookie bar if JS is not enabled, as it's a situation where we _couldn't_ set/use cookies. I wasn't around for the original decision to show the bar for no-JS users, so there might be some very good reasons for the choice, possibly legal ones, but it's probably worth looking at again at some point.

**Comment by vipickering** [comment]
@dsingleton @alexmuller Thanks for both your responses on this. For my service (Fitnote) I think, the server side route is the way to go, so I'll post back how I get on. Once I've had time to implement it and test it fully.

**Comment by timpaul** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Template will now only get major bug fixes and security patches, so I'm going to close this.
