### ISSUE TITLE
GOV.UK logo disappears if using custom colours.

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk_template#244]
If a user uses custom colours (for accessibility), the GOV.UK logo dissapears. The OGL logo and crown copyright logo also disappear, but these seem less important.

Example:
![screen shot 2016-08-30 at 12 13 09](https://cloud.githubusercontent.com/assets/2204224/18087080/2c870a04-6eab-11e6-8d52-adcc1ecb54d1.png)

Spotted in this blog post: https://accessibility.blog.gov.uk/2016/05/26/accessibility-and-me-marian-foley/

For testing, I adjusted the colours using firefox as described in Marian's blog post.

Note: there are other issues throughout GOV.UK relating to this, but this seemed specific to template.

**Comment by 36degrees** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Template will now only get major bug fixes and security patches, which wouldn't include addressing this, so I'm going to close this.

I'm happy to report that this has been fixed in GOV.UK Frontend / GOV.UK Design System for service teams going forward:

<img width="912" alt="screen shot 2018-08-23 at 10 36 03" src="https://user-images.githubusercontent.com/121939/44517721-5aacb600-a6c0-11e8-8138-a49d296631ee.png">
