### ISSUE TITLE
HTML title Language set incorrectly [i18n] [a11y]

### ISSUE THREAD

**Issue by edent** [alphagov/govuk_template#342]
Consider the page https://www.gov.uk/government/news/hinkley-point-c-to-power-six-million-uk-homes.zh - which is a Chinese language variant of https://www.gov.uk/government/news/hinkley-point-c-to-power-six-million-uk-homes

The HTML reads
```
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>欣克利角C核电站将为英国600万户家庭提供用电 - GOV.UK</title>
```

The `<title>` element needs a `lang="zh"`

The body content has the correct language tag:
`<main role="main" id="content" class="news-article" lang="zh">`

I assume this affects every page which has non-English content, eg https://www.gov.uk/government/news/young-brits-to-make-german-connections.de

This is needed to help screen-readers pronounce page titles correctly.

**Comment by MatMoore** [comment]
Hi @edent

I'll see if I can do anything about this during the GOV.UK firebreak. From talking to @36degrees it seems like we need to update the template to allow the language to be specified, and then the GOV.UK apps need to be updated to pass the language in. We only store a single locale per document, so I'll make it pass through the same lang for both the main content and the title.

**Comment by robinwhittleton** [comment]
I don’t think the template needs updating, Verify already does this (see top of https://github.com/alphagov/verify-frontend/blob/master/app/views/layouts/application.html.erb).

**Comment by nickcolley** [comment]
@robinwhittleton this is to set the `lang` attribute on the `title` element, not the `html` element.

**Comment by MatMoore** [comment]
That said, in the linked example, is it correct that lang="en" for the page? Is the intention that the page itself is considered english and only the content and title are marked as chinese?

**Comment by 36degrees** [comment]
I believe so – the navigation, page title, footer etc are all in English. As long as the areas with non-English content are marked appropriately, everything should work fine.

**Comment by edent** [comment]
I'd agree. Semantically it's an English page with Chinese content.

We can't have multilingual titles (see https://github.com/w3c/html/issues/1292) but using the primary language of the page should be suitable.

**Comment by r12a** [comment]
You probably want to use zh-Hans rather than zh, since this (looking at the example above) is Simplified Chinese, rather than Traditional Chinese writing. Specifying the script will help with automatic font selection, and maybe other things. (See https://www.w3.org/International/articles/language-tags/index#script)

**Comment by MatMoore** [comment]
We seem to be using language subtags that indicate region (es-419, zh-hk, zh-tw) but not zh-Hans or zh-Hant.

I think if we make that change we would need to do it in the publishing app (https://github.com/alphagov/whitehall) so that it's under the control of the person publishing/translation the document. Otherwise there would be a mismatch between the language stored in the backend and reported in the content API, and what gets rendered on the page.

Based on what we show in whitehall, we are using zh-tw to mean "traditional chinese" and zh-hk to mean "cantonese", which seems wrong. I think this should be looked at as a separate issue but I'm probably not going to have time to do it myself. I'm not sure if there's a team on GOV.UK that can pick it up, but if anyone wants to raise a PR against whitehall I'd be happy to point you in the right direction.

**Comment by MatMoore** [comment]
@edent https://github.com/alphagov/government-frontend/commit/fa76ae6b6318639b9d0eeeda52839c92d4d1b887 should fix this for a bunch of formats, including news articles. I can deploy this, but so far I haven't been able to get screenreaders to pick up on it when testing.

JAWS switches between voices when navigating around the content of a page, but still reads the title in english even with the lang attribute. I had a go at using voiceover as well, but I'm running an old version of OSX which doesn't seem to change languages automatically.

**Comment by edent** [comment]
@MatMoore I don't see any title tests listed at https://freedomscientific.github.io/VFO-standards-support/html.html

Might be worth filing a bug at https://github.com/FreedomScientific/VFO-standards-support/issues

Ping @stevefaulkner @LJWatson for more clues.

**Comment by timpaul** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Template will now only get major bug fixes and security patches, so I'm going to close this.

This issue has been [captured in GOV.UK Frontend here](https://github.com/alphagov/govuk-frontend/issues/971).
